name: Deploy to Railway

on: 
    push:
        branches:
            - main

jobs: 
    deploy:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - run: curl -fsSL https://railway.app/install.sh | sh
        - run: railway up --service=${{ secrets.SVC_ID }}
          env:
              RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
